#pragma once

#define MESH_CHANNEL 6

#define CONFIG_MESH_MAX_LAYER 2
#define CONFIG_MESH_AP_AUTHMODE 3 // WIFI_AUTH_WPA2_PSK
#define CONFIG_MESH_AP_CONNECTIONS 6
#define CONFIG_MESH_NON_MESH_AP_CONNECTIONS 2
#define CONFIG_MESH_ROUTE_TABLE_SIZE 50
#define CONFIG_MESH_AP_PASSWD "12345678"

#define RX_COMMAND_SIZE (128)
#define TX_SIZE (128)
#define RX_ARRAY_SIZE (128)
void mesh_app_start();